### ISSUE TITLE
Using overlaybd v0.5.0 prevents Ubuntu 18.04 from working

### ISSUE THREAD

**Issue by shuaichang** [containerd/overlaybd#116]
When using [overlaybd-0.5.0-1.x86_64.deb](https://github.com/containerd/overlaybd/releases/download/v0.5.0/overlaybd-0.5.0-1.x86_64.deb), running on a Ubuntu 18.04 host will result `GLIBC_2.28' not found`.

In our environment, it's not flexible to upgrade node image version but we still need to get overlaybd upgrades. Curious what would be the plan to continue support Ubuntu 18.04 in overlaybd?

**Comment by liulanzheng** [comment]
we will continue support if anyone needs ~

**Comment by shuaichang** [comment]
We do need the lastest overlaybd-tcmu and snapshotter to work with 18.04 as switching node image is not an option. Could you add separate deb for 18.04 in the release downloads or somehow the same deb could work for both versions.
