### ISSUE TITLE
Error when execute cmake

### ISSUE THREAD

**Issue by dbfancier** [containerd/overlaybd#121]
i don't known much about cmake， when i excute "cd build && cmake .."，it shows:
-- Configuring done
CMake Error at src/overlaybd/cache/ocf_cache/CMakeLists.txt:12 (add_library):
  No SOURCES given to target: ocf_lib

Can anyone help me with this problem? Thanks

**Comment by liulanzheng** [comment]
@dbfancier  init submodule by :  git submodule update --init

**Comment by dbfancier** [comment]
> 

thanks a lot , your method solved my promblem
