### ISSUE TITLE
v0.6.0 release does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by juliusl** [containerd/overlaybd#162]
The overlaybd-tcmu service will not start on 18.04. My guess is because release v0.6.0 was compiled on 20.04+? The workaround is to install the missing shared libraries, 

```
 apt install libaio1 libnl-3-dev libnl-genl-3-dev
```

Just for context, we are working on adding support in AKS. The default node image in AKS is Ubuntu 18.04.

**Comment by liulanzheng** [comment]
this deb package is compiled on ubuntu 18.04 using `https://github.com/containerd/overlaybd/blob/main/.github/workflows/dev-release.yml`.
Shared libraries thar overlaybd depends have to be install on the runtime environment, but the dev package is not necessary. 
So just `apt install libaio1 libnl-3 libnl-genl-3` is ok.

**Comment by juliusl** [comment]
@liulanzheng I see, can you add those deps to the .deb definition so that the package manager can install those dependencies?

**Comment by juliusl** [comment]
@liulanzheng it doesn't look like libnl-3 and libnl-genl-3 exist?

**Comment by liulanzheng** [comment]
@juliusl  there names under ubuntu 18.04 are libnl-3-200 and libnl-genl-3-200. I don't known what 200 means...

**Comment by liulanzheng** [comment]
![image](https://user-images.githubusercontent.com/16135826/218999794-0d4a505f-f325-4fc6-ba84-b9b14dd1d7f0.png)
@juliusl  now the CPACK was configured to generate dependences automatically, please try the latest development package.

**Comment by juliusl** [comment]
@liulanzheng Thanks, tested and seems to be working.
