### ISSUE TITLE
RPM package release?

### ISSUE THREAD

**Issue by juliusl** [containerd/overlaybd#163]
Are there plans to release an RPM package? I noticed that the accelerated-container-image v0.6.0 release has an .rpm binary.

**Comment by liulanzheng** [comment]
I can't find a way to automatically publish an RPM package on github action.  accelerated-container-image is a golang project, it worked for both RPM and DEB. but overlaybd didn't work well. We will try to solve this problem later, but the priority is not very high.

**Comment by liulanzheng** [comment]
@juliusl  rpm is ready, you may try the latest development release

**Comment by juliusl** [comment]
@liulanzheng Thanks I haven't had a chance to test it yet, but it's on my todo list.
