### ISSUE TITLE
Using Overlaybd in Container

### ISSUE THREAD

**Issue by qi0523** [containerd/overlaybd#177]
Is it possible to create a overlaybd‘s container in the privileged container which can use ctr command?

**Comment by HileQAQ** [comment]
Yes, it is possible. Let's assume that you have prepared the overlaybd environment on the host and mounted `containerd.sock` and the root directory of containerd (by default `/var/lib/containerd`) in the container. After that, mount `/dev/` to the container and use the overlaybd's container by using the `rpull` command of our custom version of `ctr`.
