### ISSUE TITLE
registryfs.cpp: getActualUrl

### ISSUE THREAD

**Issue by qi0523** [containerd/overlaybd#203]
`/home/runner/work/overlaybd/overlaybd/src/overlaybd/registryfs/registryfs.cpp:241|getActualUrl:Failed to get actual url [url=http://172.17.18.1:19145/v2/library/redis/blobs/sha256:c62d96ea337990a7cd656edc1a4f4f0d2e0ca460bcda50358a8e40967e8e011f][ret=404]`

l am using a simple registry which only handles  basic requests, such as manifests and blobs. So,  how to close this features?

**Comment by liulanzheng** [comment]
@qi0523  ret=404 means the corresponding blob does not found. what registry did you use?

**Comment by qi0523** [comment]
@liulanzheng i use p2p mode to download blobs. `172.17.18.1:19145` is the upstream endpoint. The downstream failed due to performing `getActualUrl` first.

**Comment by liulanzheng** [comment]
@HileQAQ  Please follow up this issue about p2p.

**Comment by HileQAQ** [comment]
@qi0523 What is the result if you ping `http://172.17.18.1:19145/v2/library/redis/blobs/sha256:c62d96ea337990a7cd656edc1a4f4f0d2e0ca460bcda50358a8e40967e8e011f`?
