### ISSUE TITLE
What is the difference between cacheConfig.registry_cache and p2pConfig.CacheConfig

### ISSUE THREAD

**Issue by qi0523** [containerd/overlaybd#294]
When using p2pConfig.CacheConfig as file's cache, does cacheConfig.registry_cache work? 

If the size of the p2pCache is exceeded, some files will be deleted by dadi-p2psever. 

When the container creates again, does dadi-p2pserver still pull from the image registry or other dadi-servers?

Thanks.

**Comment by liulanzheng** [comment]
> When using p2pConfig.CacheConfig as file's cache, does cacheConfig.registry_cache work?

If P2P is enabled, the cache of P2P will be used, and the cache of ovelaybd will not work.

> If the size of the p2pCache is exceeded, some files will be deleted by dadi-p2psever.
> 
> When the container creates again, does dadi-p2pserver still pull from the image registry or other dadi-servers?

yes
