### ISSUE TITLE
Missing extended attributes after userspace conversion 

### ISSUE THREAD

**Issue by juliusl** [containerd/overlaybd#301]
### What happened in your environment?

/usr/bin/ping is missing cap. permissions, causes a permission issue when using ping

### What did you expect to happen?

All extended attributes are preserved after conversion 

### How can we reproduce it?

Centos image

### What is the version of your Overlaybd?

Latest

### What is your OS environment?

Mariner

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by yuchen0cc** [comment]
fix in #302
further discussion https://github.com/containerd/accelerated-container-image/issues/251
