### ISSUE TITLE
Add Custom / Descriptive HTTP User-Agent for Overlaybd

### ISSUE THREAD

**Issue by estebanreyl** [containerd/overlaybd#328]
### What is the version of your Overlaybd

v1.0.10

### What would you like to be added?

We have noticed that overlaybd seems to make requests using userAgent EASE/0.21.6. This is not super clear from a service / registry standpoint as pointing to the overlaybd project which makes it difficult for registries to identify traffic and provide feedback to customers. If possible, Id like to be able to specify the overlaybd user agent through a config or if the decision is made that users shouldn't have control to at least have a descriptive useragent.

For context on this header:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

Some examples of User-Agent Headers we see in azure:
- Docker has very verbose user agents with a ton of info like:
```
docker/20.10.25 go/go1.20.10 git-commit/5df983c kernel/5.15.138.1-4.cm2 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.25 \(linux\))
```
- Containerd useragents are a bit less verbose and look like:
```
containerd/1.7.2
```

### Why is this needed for Overlaybd?

Including this will help registries identify overlaybd streaming traffic to provide feedback and better support for users.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by BigVan** [comment]
It's a good suggestion.

**Comment by BigVan** [comment]
https://github.com/alibaba/PhotonLibOS/issues/469
