### ISSUE TITLE
Erofs Gitee Dependency Can Result in Build Issues Due to Compliance Reasons

### ISSUE THREAD

**Issue by estebanreyl** [containerd/overlaybd#337]
### What is the version of your Overlaybd

commit 0edcc6b7c4f80bdf9606e4ad1027a28dedb17e42

### What would you like to be added?

We have encountered a situation where due to compliance and security reasons gitee is not currently accessible within certain microsoft build systems. This has made it difficult to build the overlaybd project there in light of the erofs (https://gitee.com/anolis/erofs-utils.git/) dependency as it will fail to download. We are trying to resolve this internally but would like to bring this up in the event that it is possible to rehost this dependency to github or a fork there. 

### Why is this needed for Overlaybd?

While we realize this is not strictly an overlaybd problem, we do want to bring the issue to light to at least discuss options.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by hsiangkao** [comment]
it will switch to git.kernel.org repo soon.
