### ISSUE TITLE
Update doc for installing dependences to support DSA

### ISSUE THREAD

**Issue by liulanzheng** [containerd/overlaybd#72]
For pr #69 brought in new dependences and resulted compile error.  New dependences should be added to sector `Build From Source` of README.md.

**Comment by beef9999** [comment]
@liulanzheng src/overlaybd/fs/zfile/crc32/README has clarified how to build DSA.

And in normal circumstances, this build would be skipped because of lack of DSA device. What happened in your environment?

**Comment by liulanzheng** [comment]
@beef9999 
![image](https://user-images.githubusercontent.com/16135826/143417613-5eaf82f6-9d77-4781-806e-b9051e989aee.png)
And after i installed libuuid-devel, compilation succeeded.

**Comment by beef9999** [comment]
Fixed by https://github.com/containerd/overlaybd/pull/73
