### ISSUE TITLE
share local caches under different repo

### ISSUE THREAD

**Issue by bengbeng-pp** [containerd/overlaybd#80]
Just now, obdconv supports the  layer caching during image conversion. pr：https://github.com/containerd/accelerated-container-image/pull/98.  
Are there any plans to share local caches under different repo?

Please refer to https://github.com/containerd/overlaybd/issues/68
![1644997233264-image](https://user-images.githubusercontent.com/53809897/154218320-2af5ef70-5103-4479-a9b0-47b3193b23fc.png)

**Comment by liulanzheng** [comment]
@BigVan  #81 cc

**Comment by liulanzheng** [comment]
I implemented it, @BigVan cc
