### ISSUE TITLE
overlaybd-tcmu crash

### ISSUE THREAD

**Issue by wxx213** [containerd/overlaybd#86]
After we sync the latest overlaybd codes(until a1390faccb1c2d82208db4987ac76c046620f384), the overlaybd-tcmu crash when bootup.

OS version: CentOS Linux release 7.4.1708 (Core)
kernel version: 4.18.0

The backtrace:
`(gdb) bt
#0  0x00007f5194ac4387 in raise () at /lib64/libc.so.6
#1  0x00007f5194ac5a78 in abort () at /lib64/libc.so.6
#2  0x00007f5194abd1a6 in __assert_fail_base () at /lib64/libc.so.6
#3  0x00007f5194abd252 in  () at /lib64/libc.so.6
#4  0x00000000004f1554 in alog_format::FMTLogBuffer::printf_fmt<60, 81, , int, alog_noop>(alog_format::ALogFMTString<alog_format::seq<81> >, int const&, alog_noop const&) (this=0x7f518de75f10, fmt=..., x=@0x7f518de770c8: -1, xs#0=...) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:533
#5  0x00000000004f126b in alog_format::next<true, 60>::printf_fmt<alog_format::ALogFMTString<alog_format::seq<81> >, unsigned int, int, alog_noop>(alog_format::FMTLogBuffer&, alog_format::ALogFMTString<alog_format::seq<81> >, unsigned int const&, int const&, alog_noop const&) (log=..., fmt=..., x=@0x7f518de770cc: 3473955946, xs#0=@0x7f518de770c8: -1, xs#1=...) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:504
#6  0x00000000004f0cd8 in alog_format::FMTLogBuffer::printf_fmt<50, 59, 81, unsigned int, int, alog_noop>(alog_format::ALogFMTString<alog_format::seq<59, 81> >, unsigned int const&, int const&, alog_noop const&) (this=0x7f518de75f10, fmt=..., x=@0x7f518de770cc: 3473955946, xs#0=@0x7f518de770c8: -1, xs#1=...)
    at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:537
#7  0x00000000004f059b in alog_format::next<true, 50>::printf_fmt<alog_format::ALogFMTString<alog_format::seq<59, 81> >, unsigned int, unsigned int, int, alog_noop>(alog_format::FMTLogBuffer&, alog_format::ALogFMTString<alog_format::seq<59, 81> >, unsigned int const&, unsigned int const&, int const&, alog_noop const&) (log=..., fmt=..., x=@0x7f518de76fbc: 6619904, xs#0=@0x7f518de770cc: 3473955946, xs#1=@0x7f518de770c8: -1, xs#2=...) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:504
#8  0x00000000004efa7d in alog_format::FMTLogBuffer::printf_fmt<37, 49, 59, 81, unsigned int, unsigned int, int, alog_noop>(alog_format::ALogFMTString<alog_format::seq<49, 59, 81> >, unsigned int const&, unsigned int const&, int const&, alog_noop const&) (this=0x7f518de75f10, fmt=..., x=@0x7f518de76fbc: 6619904, xs#0=@0x7f518de770cc: 3473955946, xs#1=@0x7f518de770c8: -1, xs#2=...) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:537
#9  0x00000000004eeeac in alog_format::next<true, 37>::printf_fmt<alog_format::ALogFMTString<alog_format::seq<49, 59, 81> >, unsigned long, unsigned int, unsigned int, int, alog_noop>(alog_format::FMTLogBuffer&, alog_format::ALogFMTString<alog_format::seq<49, 59, 81> >, unsigned long const&, unsigned int const&, unsigned int const&, int const&, alog_noop const&) (log=..., fmt=..., x=@0x7f518de97170: 38113, xs#0=@0x7f518de76fbc: 6619904, xs#1=@0x7f518de770cc: 3473955946, xs#2=@0x7f518de770c8: -1, xs#3=...)
    at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:504
#10 0x00000000004edbb0 in alog_format::FMTLogBuffer::printf_fmt<26, 36, 49, 59, 81, unsigned long, unsigned int, unsigned int, int, alog_noop>(alog_format::ALogFMTString<alog_format::seq<36, 49, 59, 81> >, unsigned long const&, unsigned int const&, unsigned int const&, int const&, alog_noop const&) (this=0x7f518de75f10, fmt=..., x=@0x7f518de97170: 38113, xs#0=@0x7f518de76fbc: 6619904, xs#1=@0x7f518de770cc: 3473955946, xs#2=@0x7f518de770c8: -1, xs#3=...)
    at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:537
#11 0x00000000004ec2a7 in alog_format::next<true, 26>::printf_fmt<alog_format::ALogFMTString<alog_format::seq<36, 49, 59, 81> >, long, unsigned long, unsigned int, unsigned int, int, alog_noop>(alog_format::FMTLogBuffer&, alog_format::ALogFMTString<alog_format::seq<36, 49, 59, 81> >, long const&, unsigned long const&, unsigned int const&, unsigned int const&, int const&, alog_noop const&) (log=..., fmt=..., x=@0x7f518de87138: 0, xs#0=@0x7f518de97170: 38113, xs#1=@0x7f518de76fbc: 6619904, xs#2=@0x7f518de770cc: 3473955946, xs#3=@0x7f518de770c8: -1, xs#4=...) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:504
#12 0x00000000004ea0f9 in alog_format::FMTLogBuffer::printf_fmt<0, 25, 36, 49, 59, 81, long, unsigned long, unsigned int, unsigned int, int, alog_noop>(alog_format::ALogFMTString<alog_format::seq<25, 36, 49, 59, 81> >, long const&, unsigned long const&, unsigned int const&, unsigned int const&, int const&, alog_noop const&) (this=0x7f518de75f10, fmt=..., x=@0x7f518de87138: 0, xs#0=@0x7f518de97170: 38113, xs#1=@0x7f518de76fbc: 6619904, xs#2=@0x7f518de770cc: 3473955946, xs#3=@0x7f518de770c8: -1, xs#4=...)
    at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:537
#13 0x00000000004e108f in __log__<alog_format::seq<25, 36, 49, 59, 81>, 80, long&, unsigned long const&, unsigned int, unsigned int&, int&, alog_noop>(int, ILogOutput *, co---Type <return> to continue, or q <return> to quit---
nst Prologue &, const char (&)[80], long &, const unsigned long &, <unknown type in /opt/overlaybd/bin/overlaybd-tcmu, CU 0x300276, DIE 0x332003>, unsigned int &, int &, <unknown type in /opt/overlaybd/bin/overlaybd-tcmu, CU 0x300276, DIE 0x332030>) (level=3, output=
    0x874720 <default_log_output_file>, prolog=..., fmt=..., xs#0=@0x7f518de87138: 0, xs#1=@0x7f518de97170: 38113, xs#2=<unknown type in /opt/overlaybd/bin/overlaybd-tcmu, CU 0x300276, DIE 0x332003>, xs#3=@0x7f518de770cc: 3473955946, xs#4=@0x7f518de770c8: -1, xs#5=<unknown type in /opt/overlaybd/bin/overlaybd-tcmu, CU 0x300276, DIE 0x332030>) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:574
#14 0x00000000004e717a in ZFile::CompressionFile::pread(void*, unsigned long, long)::{lambda(ILogOutput*)#3}::operator()(ILogOutput*) const (__closure=0x7f518de97198, __output___LINE__=0x874720 <default_log_output_file>) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/zfile.cpp:426
#15 0x00000000004e8ac4 in LogBuilder<ZFile::CompressionFile::pread(void*, unsigned long, long)::{lambda(ILogOutput*)#3}>::~LogBuilder() (this=0x7f518de97190, __in_chrg=<optimized out>) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/../../alog.h:596
#16 0x00000000004e76fa in ZFile::CompressionFile::pread(void*, unsigned long, long) (this=0x3ea6050, buf=0x7f518de98000, count=4096, offset=0)
    at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/zfile/zfile.cpp:426
#17 0x00000000004562ce in FileSystem::SwitchFile::pread(void*, unsigned long, long) (this=0x3ea6110, buf=0x7f518de98000, count=4096, offset=0)
    at /rpmbuild/BUILD/overlaybd-0.4.1/src/switch_file.cpp:135
#18 0x00000000004b2662 in LSMT::verify_ht(FileSystem::IFile*, char*) (file=0x3ea6110, buf=0x7f518de98000 "")
    at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/lsmt/file.cpp:859
#19 0x00000000004b2aad in LSMT::do_load_index(LSMT::IFile*, LSMT::HeaderTrailer*, bool) (file=0x3ea6110, pheader_trailer=0x3eeffd8, trailer=true)
    at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/lsmt/file.cpp:871
#20 0x00000000004b4753 in LSMT::do_parallel_load_index(void*) (param=0x7ffd46696460) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/fs/lsmt/file.cpp:1086
#21 0x0000000000478c2f in photon::thread::go() (this=0x7f518de99800) at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/photon/thread.cpp:100
#22 0x0000000000476ace in photon::thread_stub() () at /rpmbuild/BUILD/overlaybd-0.4.1/src/overlaybd/photon/thread.cpp:255
#23 0x0000000000000000 in  ()`

**Comment by BigVan** [comment]
It seems log format is invalid when crc mismatch....  I have fixed it, please try again:
https://github.com/containerd/overlaybd/pull/87/files

**Comment by wxx213** [comment]
> It seems log format is invalid when crc mismatch.... I have fixed it, please try again: https://github.com/containerd/overlaybd/pull/87/files

I works, thanks.
