### ISSUE TITLE
How to clear the local layer cache

### ISSUE THREAD

**Issue by bengbeng-pp** [containerd/overlaybd#88]
How to clear the local layer cache ？
Can I delete the cached files in the ’registryCacheDir‘  directory directly? Is the relevant information stored in the memory?

**Comment by beef9999** [comment]
Yes you can, but remember to restart the overlaybd service.

Nothing will remain in memory except the OS page cache.

**Comment by bengbeng-pp** [comment]
Does pagecache refer to pagecache of  local layer cache files?

**Comment by beef9999** [comment]
Yes, removing files on will not erase their page cache, you have to drop them manually and wait enough time til the OS recycles them.

**Comment by liulanzheng** [comment]
@beef9999  i think there's no need to care about page cache.

**Comment by beef9999** [comment]
That's generally true if we are not running some kind of performance tests. So I was asking his purpose.

**Comment by bengbeng-pp** [comment]
Similar to gc, periodically release useless cache files to free up space

**Comment by bengbeng-pp** [comment]
Asking a question unrelated to this question, does overlaybd restart affect running containers?

**Comment by beef9999** [comment]
iSCSI protocol has the ability to reconnect, block device will remain unaffected if the iSCSI target becomes alive in time.

**Comment by beef9999** [comment]
> Similar to gc, periodically release useless cache files to free up space

We have ensured the cache does not exceed maximum amount of the user specified size, an internal eviction will be running.

Of course we will be appreciate if you contribute more intelligent code to do the gc.

**Comment by bengbeng-pp** [comment]
I understand that overlaybd ensures cache max storage space .
Because we want to save the information of the base image, delete other data first.
