### ISSUE TITLE
Refactor with PhotonLibOS

### ISSUE THREAD

**Issue by liulanzheng** [containerd/overlaybd#97]
Since [PhotonLibOS](https://github.com/alibaba/PhotonLibOS) is official released, overlaybd will be reconstructed based on the latest photon.
Photon is a high-efficiency LibOS framework, based on a set of carefully selected C++ libs. Overlaybd is now based on an early version of photon. After refactoring, overlaybd will get the latest capabilities of photon.

**Comment by BigVan** [comment]
Woooooooooow, that's great.
We can add more information about PhotonLibOS in our introduction.
